# yaml 配置实例
version: '3'
services:
  node-exporter:
    image: prom/node-exporter
    restart: always
    expose:
      - "9100"
    networks: 
      serviceMonitor:
        ipv4_address: 172.30.1.51
    container_name: node-exporter

  consul:
    image: consul
    container_name: consul
    restart: always
    ports:
     - "8500:8500"
    volumes:
     - /etc/localtime:/etc/localtime
     - /home/zwx/serviceMonitor/consul/config:/consul/config
     - /home/zwx/serviceMonitor/consul/data/:/consul/data/
    networks: 
      serviceMonitor:
        ipv4_address: 172.30.1.50
    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "5" # 最多5个文件
    depends_on:
      - prometheus
  
  prometheus:
    image: prom/prometheus
    container_name: myprom
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/zwx/serviceMonitor/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      serviceMonitor:
        ipv4_address: 172.30.1.52
    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "5" # 最多5个文件
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - "serviceMonitor"
    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "5" # 最多5个文件

networks:
 serviceMonitor:
  external: true
