global:
  scrape_interval: 60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
 
  - job_name: linux
    static_configs:
      - targets: ['172.30.1.51:9100']
        labels:
          instance: '172.30.1.51'

  - job_name: consul-prometheus
    consul_sd_configs:
      - server:   '172.30.1.50:8500'
        services: []
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:  .*prometheus.*
        action:  keep  